// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/my_list.dart';
import 'models/poi.dart';
import 'models/poi_image.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 2564830902377691936),
    name: 'MyList',
    lastPropertyId: const obx_int.IdUid(4, 4018009328234177358),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2841149807284793275),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5416042487100886110),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7891920259085479833),
        name: 'isDefault',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4018009328234177358),
        name: 'note',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'poiList',
        srcEntity: 'Poi',
        srcField: 'lists',
      ),
    ],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 8830379915544507035),
    name: 'Poi',
    lastPropertyId: const obx_int.IdUid(15, 6106478929915493272),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5546610703469631195),
        name: 'id',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5912105956962268458),
        name: 'type',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 43484478466458181),
        name: 'subtype',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3888967754307160017),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3174316429172802148),
        name: 'city',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 5552791533464306198),
        name: 'province',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 5640203255228568499),
        name: 'region',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 1913581569097228814),
        name: 'country',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 2324446696472440668),
        name: 'countrycode',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 6588607892471418106),
        name: 'obxId',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 7505679922691171486),
        name: 'lat',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 6554320035092931751),
        name: 'lng',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 6106478929915493272),
        name: 'categoryName',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[
      obx_int.ModelRelation(
        id: const obx_int.IdUid(1, 4260548416396553619),
        name: 'images',
        targetId: const obx_int.IdUid(3, 2691727041825612039),
      ),
      obx_int.ModelRelation(
        id: const obx_int.IdUid(2, 8403936394981984254),
        name: 'lists',
        targetId: const obx_int.IdUid(1, 2564830902377691936),
      ),
    ],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 2691727041825612039),
    name: 'PoiImage',
    lastPropertyId: const obx_int.IdUid(3, 2953111697413067060),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1680643708531825174),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 186744534902447545),
        name: 'thumbnail',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2953111697413067060),
        name: 'imageUrl',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(3, 2691727041825612039),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(2, 8403936394981984254),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [6907666138422418640, 8356680331267662623],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    MyList: obx_int.EntityDefinition<MyList>(
      model: _entities[0],
      toOneRelations: (MyList object) => [],
      toManyRelations: (MyList object) => {
        obx_int.RelInfo<Poi>.toManyBacklink(2, object.id): object.poiList,
      },
      getId: (MyList object) => object.id,
      setId: (MyList object, int id) {
        object.id = id;
      },
      objectToFB: (MyList object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        final noteOffset = fbb.writeString(object.note);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addBool(2, object.isDefault);
        fbb.addOffset(3, noteOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final isDefaultParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          8,
          false,
        );
        final noteParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final object = MyList(
          name: nameParam,
          isDefault: isDefaultParam,
          note: noteParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        obx_int.InternalToManyAccess.setRelInfo<MyList>(
          object.poiList,
          store,
          obx_int.RelInfo<Poi>.toManyBacklink(2, object.id),
        );
        return object;
      },
    ),
    Poi: obx_int.EntityDefinition<Poi>(
      model: _entities[1],
      toOneRelations: (Poi object) => [],
      toManyRelations: (Poi object) => {
        obx_int.RelInfo<Poi>.toMany(1, object.obxId): object.images,
        obx_int.RelInfo<Poi>.toMany(2, object.obxId): object.lists,
      },
      getId: (Poi object) => object.obxId,
      setId: (Poi object, int id) {
        object.obxId = id;
      },
      objectToFB: (Poi object, fb.Builder fbb) {
        final idOffset = fbb.writeString(object.id);
        final typeOffset = object.type == null
            ? null
            : fbb.writeString(object.type!);
        final subtypeOffset = object.subtype == null
            ? null
            : fbb.writeString(object.subtype!);
        final nameOffset = fbb.writeString(object.name);
        final cityOffset = object.city == null
            ? null
            : fbb.writeString(object.city!);
        final provinceOffset = object.province == null
            ? null
            : fbb.writeString(object.province!);
        final regionOffset = object.region == null
            ? null
            : fbb.writeString(object.region!);
        final countryOffset = object.country == null
            ? null
            : fbb.writeString(object.country!);
        final countrycodeOffset = object.countrycode == null
            ? null
            : fbb.writeString(object.countrycode!);
        final categoryNameOffset = fbb.writeString(object.categoryName);
        fbb.startTable(16);
        fbb.addOffset(1, idOffset);
        fbb.addOffset(2, typeOffset);
        fbb.addOffset(3, subtypeOffset);
        fbb.addOffset(4, nameOffset);
        fbb.addOffset(5, cityOffset);
        fbb.addOffset(6, provinceOffset);
        fbb.addOffset(7, regionOffset);
        fbb.addOffset(8, countryOffset);
        fbb.addOffset(9, countrycodeOffset);
        fbb.addInt64(10, object.obxId);
        fbb.addFloat64(12, object.lat);
        fbb.addFloat64(13, object.lng);
        fbb.addOffset(14, categoryNameOffset);
        fbb.finish(fbb.endTable());
        return object.obxId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final typeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final subtypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final cityParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final provinceParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final regionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final countryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final countrycodeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final categoryNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 32, '');
        final latParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          28,
          0,
        );
        final lngParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          30,
          0,
        );
        final object = Poi(
          id: idParam,
          type: typeParam,
          subtype: subtypeParam,
          name: nameParam,
          city: cityParam,
          province: provinceParam,
          region: regionParam,
          country: countryParam,
          countrycode: countrycodeParam,
          categoryName: categoryNameParam,
          lat: latParam,
          lng: lngParam,
        )..obxId = const fb.Int64Reader().vTableGet(buffer, rootOffset, 24, 0);
        obx_int.InternalToManyAccess.setRelInfo<Poi>(
          object.images,
          store,
          obx_int.RelInfo<Poi>.toMany(1, object.obxId),
        );
        obx_int.InternalToManyAccess.setRelInfo<Poi>(
          object.lists,
          store,
          obx_int.RelInfo<Poi>.toMany(2, object.obxId),
        );
        return object;
      },
    ),
    PoiImage: obx_int.EntityDefinition<PoiImage>(
      model: _entities[2],
      toOneRelations: (PoiImage object) => [],
      toManyRelations: (PoiImage object) => {},
      getId: (PoiImage object) => object.id,
      setId: (PoiImage object, int id) {
        object.id = id;
      },
      objectToFB: (PoiImage object, fb.Builder fbb) {
        final thumbnailOffset = object.thumbnail == null
            ? null
            : fbb.writeString(object.thumbnail!);
        final imageUrlOffset = object.imageUrl == null
            ? null
            : fbb.writeString(object.imageUrl!);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, thumbnailOffset);
        fbb.addOffset(2, imageUrlOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final thumbnailParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 6);
        final imageUrlParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final object = PoiImage(
          thumbnail: thumbnailParam,
          imageUrl: imageUrlParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [MyList] entity fields to define ObjectBox queries.
class MyList_ {
  /// See [MyList.id].
  static final id = obx.QueryIntegerProperty<MyList>(
    _entities[0].properties[0],
  );

  /// See [MyList.name].
  static final name = obx.QueryStringProperty<MyList>(
    _entities[0].properties[1],
  );

  /// See [MyList.isDefault].
  static final isDefault = obx.QueryBooleanProperty<MyList>(
    _entities[0].properties[2],
  );

  /// See [MyList.note].
  static final note = obx.QueryStringProperty<MyList>(
    _entities[0].properties[3],
  );
}

/// [Poi] entity fields to define ObjectBox queries.
class Poi_ {
  /// See [Poi.id].
  static final id = obx.QueryStringProperty<Poi>(_entities[1].properties[0]);

  /// See [Poi.type].
  static final type = obx.QueryStringProperty<Poi>(_entities[1].properties[1]);

  /// See [Poi.subtype].
  static final subtype = obx.QueryStringProperty<Poi>(
    _entities[1].properties[2],
  );

  /// See [Poi.name].
  static final name = obx.QueryStringProperty<Poi>(_entities[1].properties[3]);

  /// See [Poi.city].
  static final city = obx.QueryStringProperty<Poi>(_entities[1].properties[4]);

  /// See [Poi.province].
  static final province = obx.QueryStringProperty<Poi>(
    _entities[1].properties[5],
  );

  /// See [Poi.region].
  static final region = obx.QueryStringProperty<Poi>(
    _entities[1].properties[6],
  );

  /// See [Poi.country].
  static final country = obx.QueryStringProperty<Poi>(
    _entities[1].properties[7],
  );

  /// See [Poi.countrycode].
  static final countrycode = obx.QueryStringProperty<Poi>(
    _entities[1].properties[8],
  );

  /// See [Poi.obxId].
  static final obxId = obx.QueryIntegerProperty<Poi>(
    _entities[1].properties[9],
  );

  /// See [Poi.lat].
  static final lat = obx.QueryDoubleProperty<Poi>(_entities[1].properties[10]);

  /// See [Poi.lng].
  static final lng = obx.QueryDoubleProperty<Poi>(_entities[1].properties[11]);

  /// See [Poi.categoryName].
  static final categoryName = obx.QueryStringProperty<Poi>(
    _entities[1].properties[12],
  );

  /// see [Poi.images]
  static final images = obx.QueryRelationToMany<Poi, PoiImage>(
    _entities[1].relations[0],
  );

  /// see [Poi.lists]
  static final lists = obx.QueryRelationToMany<Poi, MyList>(
    _entities[1].relations[1],
  );
}

/// [PoiImage] entity fields to define ObjectBox queries.
class PoiImage_ {
  /// See [PoiImage.id].
  static final id = obx.QueryIntegerProperty<PoiImage>(
    _entities[2].properties[0],
  );

  /// See [PoiImage.thumbnail].
  static final thumbnail = obx.QueryStringProperty<PoiImage>(
    _entities[2].properties[1],
  );

  /// See [PoiImage.imageUrl].
  static final imageUrl = obx.QueryStringProperty<PoiImage>(
    _entities[2].properties[2],
  );
}
